services:
  smarttaskapi:
    build: ./SmartTaskAPI
    env_file:
      - .env
    container_name: smarttaskapi
    ports:
      - "5284:80"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  postgres:
    image: postgres:latest
    container_name: smarttaskdb-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 20s

  ml-service:
    build: ./ml-microservice
    container_name: smarttask-ml
    ports:
      - "5001:5000"
    depends_on:
      smarttaskapi:
        condition: service_healthy
    environment:
      DOTNET_API_URL: http://smarttaskapi:80

volumes:
  postgres_data:

networks:
  default:
    name: smarttask-network
