name: Docker Build & Push

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build API Image
        run: docker build -t ghcr.io/${{ github.repository }}/smarttaskapi:latest ./SmartTaskAPI

      - name: Build ML Image
        run: docker build -t ghcr.io/${{ github.repository }}/ml-microservice:latest ./ml-microservice

      - name: Push Images
        run: |
          docker push ghcr.io/${{ github.repository }}/smarttaskapi:latest
          docker push ghcr.io/${{ github.repository }}/ml-microservice:latest
